//
// AddLiquorRequestParams.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AddLiquorRequestParams: Codable {

    public var name: String
    public var fileName: String
    public var image: String

    public init(name: String, fileName: String, image: String) {
        self.name = name
        self.fileName = fileName
        self.image = image
    }


}

